/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_6 (
    input [3:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h1: begin
        segs = 8'h06;
      end
      3'h5: begin
        segs = 8'h6d;
      end
      4'ha: begin
        segs = 8'h77;
      end
      4'hb: begin
        segs = 8'h73;
      end
      4'hc: begin
        segs = 8'h38;
      end
      4'hd: begin
        segs = 8'h5e;
      end
      4'he: begin
        segs = 8'h79;
      end
      4'hf: begin
        segs = 8'h71;
      end
      default: begin
        segs = 8'h00;
      end
    endcase
  end
endmodule
